### PR TITLE
Mint Signup page - clone

### PR DESCRIPTION
**Pull request by cgcarlosg**
## What?
We went to Mint.com’s signup page and set up a GitHub repository for this project 
We created a HTML structure for the project.
We styled the HTML document to look like the real webpage.
We pushed our solution to GitHub repository.

## Why?
These changes completed the user sign up page for the mint.com clone sign up page.

## How?
We applied the CSS styling to the HTML structure to make it look like the original sign up page on the mint.com website.

## Testing?
We run the linters checks against our code to make sure there were no errors and created a github page for our project tested it remotely and it was running properly.

### CODE REVIEW

**Comment by umairarshadbutt** [comment]
##
## Pull Request under review by Umair Arshad (TSE)

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @cgcarlosg and @gango-anan
Such a remarkable project you made :+1: ! 
We, however, do have a few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly work on the suggested changes 👇.
- [ ] ~~Linter is not properly integrated. Please add .stylelintrc.json and  .hintrc. For more understanding visit [Microverse linters-confi](https://github.com/microverseinc/linters-config/tree/master/html-css)~~

- [ ] Make your pull request description more descriptive.

##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you stick at any point or have any questions, let me know on slack at any time. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Comment by umairarshadbutt** [comment]
Hi @cgcarlosg and @gango-anan
Sorry for my suggestion about linters integration. Now required change is just making your pull request description more descriptive
##
**If you stick at any point or have any questions, let me know on slack at any time. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Review by teekaytech — APPROVED** [review]
# Status: Approved :green_circle: 

### Congratulations team, this project has passed all the mandatory requirements. It is therefore approved :heavy_check_mark:

**Comment(s)**
- Your effort in implementing a descriptive README file is commendable. However, your readme will look more professional if you use [this template](https://github.com/microverseinc/readme-template).
- Also, always pay attention to the details of each project. Things like spaces between elements (using paddings and margins), as seen in the original page should be taken care of in your clone.

### Again, congratulations, you can merge to master.
**Good luck with your next project.**

* * *

**I'm @taofeekolalere on slack.
Happy Coding :man_technologist:**

**Comment by gango-anan** [comment]
Project completed and approved, pull request closed.

**Pull request merged**
